Fix handling of namespaces in the node tree
ros-visualization/rqt_reconfigure pull request #132
Opened 2023-08-27 21:31 UTC by nlamprian

Fixes the addition and removal of nodes.

Before
![before](https://github.com/ros-visualization/rqt_reconfigure/assets/2074154/7b30f785-31c8-4da1-9c85-1c986a22515f)
After
![after](https://github.com/ros-visualization/rqt_reconfigure/assets/2074154/56d28f05-19d2-4058-af0a-5156458c754d)

2023-08-27 21:34 UTC, nlamprian commented on src/rqt_reconfigure/node_selector_widget.py
> +        for i in range(treenodeitem_parent.rowCount()):
- Finds the treenode with the associated namespace
- Creates a new namespace/treenode only if one doesn't already exist

2023-08-27 21:35 UTC, nlamprian commented on src/rqt_reconfigure/node_selector_widget.py
> -                self._rootitem.removeRow(i)
This removed all nodes under the namespace of the node that should have been removed.

2023-08-27 21:37 UTC, nlamprian commented on src/rqt_reconfigure/node_selector_widget.py
> -        for i in reversed(range(0, self._rootitem.rowCount())):
This iteration is not valid anymore as the row count of the rootitem is now the number of the first-level children and not the number of all children/nodes.

2023-08-27 21:40 UTC, nlamprian commented on src/rqt_reconfigure/treenode_qstditem.py
> +        return copy.copy(self._list_treenode_names)
The list is being mutating in _add_children_treenode

2023-08-28 13:14 UTC, clalancette requested changes
Overall, this looks like a great fixup.  I've left a few concerns, but nothing major.

2023-08-28 13:14 UTC, clalancette commented on src/rqt_reconfigure/node_selector_widget.py
> +        # Iterate over all the indexes
I don't necessarily agree with this change.  "all of the indexes" is fine here.  I'd recommend leaving this as-is.

2023-08-28 13:14 UTC, clalancette commented on src/rqt_reconfigure/node_selector_widget.py
> -        item_widget = None
I don't think this change is correct, or, at least, this definitely changes the behavior.

If `item_child.get_param_client_widget()` throws an exception, now `item_widget` will throw a `NameError` below, rather than being a "None" in the debug log (and being emitted).

Could you explain the reasoning behind this change?

2023-08-28 13:14 UTC, clalancette commented on src/rqt_reconfigure/param_api.py
> +    # Get all the service provided by a node (node_name)
```suggestion
    # Get all of the services provided by a node (node_name)
```

2023-08-28 14:22 UTC, nlamprian commented on src/rqt_reconfigure/node_selector_widget.py
> -        item_widget = None
Your comments are all about changes suggested by the IDE. In particular to this one, item_widget always takes whatever value is returned by `item_child.get_param_client_widget()`. Notice that the exception is re-raised; the code does not continue in case of an exception.

2023-08-28 14:25 UTC, clalancette commented on src/rqt_reconfigure/node_selector_widget.py
> -        item_widget = None
Oh, really good point.  Sorry, I missed that.

Given that we are doing a `try..except Exception as e: raise e`, I think we can just get rid of the `try..except` block completely; that is the default behavior.

2023-08-28 15:02 UTC, nlamprian commented on src/rqt_reconfigure/node_selector_widget.py
> +        # Iterate over all the indexes
Do you still want these reverted?

2023-08-28 15:06 UTC, clalancette approved these changes
Thanks for iterating!  I'll run CI on this next.

2023-08-28 15:07 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19406)](http://ci.ros2.org/job/ci_linux/19406/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13934)](http://ci.ros2.org/job/ci_linux-aarch64/13934/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20127)](http://ci.ros2.org/job/ci_windows/20127/)

2023-08-28 16:15 UTC, merged

2023-08-28 17:29 UTC, nlamprian commented
Please consider backporting it

2023-09-14 08:49 UTC, quarkytale commented
@nlamprian What all distros you're hoping to have this in?

2023-09-14 09:10 UTC, MatthijsBurgh commented
I think we should always try to backport to all supported distros, so Humble and Iron if I am correct.

2024-01-24 12:56 UTC, nlamprian commented
@quarkytale any news?

2026-09-24 18:31 UTC, andrewbest-tri commented
@ahcorde 

Reviving an old thread, but this bug still reproduces on humble. I have manually ported this change and tested locally. It still looks good to me. could a mainter try to run "@Mergifyio backport humble" on this PR? seems like that's what was not decided on? The thread here shows a willingness to backport. If you prefer to review a manual PR, i can push my test branch up instead.

2026-09-25 06:41 UTC, MatthijsBurgh commented
https://github.com/Mergifyio backport humble

2026-09-25 15:48 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy kilted lyrical